### ISSUE TITLE
שגיאה עם קובץ שאינו WAV

### ISSUE THREAD

**Issue by start-life** [ShmuelRonen/hebrew_whisper#6]
העלתי קובץ MP3 ועדיין יש את השגיאה הזו: (יש לציין שעם קובץ WAV זה עובד)

C:\zxcv\hebrew_whisper\venv\Lib\site-packages\transformers\models\whisper\modeling_whisper.py:697: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
C:\zxcv\hebrew_whisper\venv\Lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\gradio\processing_utils.py", line 337, in audio_from_file
    audio = AudioSegment.from_file(filename)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z5050\miniconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\z5050\miniconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\gradio\route_utils.py", line 233, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\gradio\blocks.py", line 1604, in process_api
    inputs = await anyio.to_thread.run_sync(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\gradio\blocks.py", line 1335, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\gradio\components\audio.py", line 205, in preprocess
    sample_rate, data = processing_utils.audio_from_file(temp_file_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\hebrew_whisper\venv\Lib\site-packages\gradio\processing_utils.py", line 347, in audio_from_file
    raise RuntimeError(msg) from e
RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.

**Comment by ShmuelRonen** [comment]
Try:
Activate the venv: venv\scripts\activate
pip install ffmpeg-python
