### ISSUE TITLE
לא עובד.

### ISSUE THREAD

**Issue by UberStorm** [ShmuelRonen/hebrew_whisper#7]
היי,
מריץ שלל גרסאות של וויספר על המחשב אבל לא משנה מה הGIT הזה לא עובד לי.
בכל פעם שאני לוחץ על sumbit אני מקבל את ההודעה הבאה ולאחר מכן כלום לא קורה, גם לאחר שעות:
To create a public link, set `share=True` in `launch()`.
Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.
E:\hebrew_whisper\venv\lib\site-packages\transformers\models\whisper\modeling_whisper.py:694: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

משתמש במחשב עם כרטיס מסך RTX 4070 Ti.

**Comment by ShmuelRonen** [comment]
אינני מצליח לשחזר את הבעיה אצלי. כמו כן הריפו עובד אצל הרבה אנשים ללא בעיה. 
האם נוצר venv בתוך הפולדר?

**Comment by ShmuelRonen** [comment]
שאלה נוספת. האם השורות האלו מופיעות אצלך:

Requirements installed.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.52s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by UberStorm** [comment]
> שאלה נוספת. האם השורות האלו מופיעות אצלך:
> 
> Requirements installed. Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:03<00:00, 1.52s/it] Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.

היי,
התשובה לשתי השאלות היא כן.
הרצתי גם דרך קובץ הBAT וגם ידנית ואין הבדל.
ניסיתי גם להוריד את זה מספר פעמים לכוננים שונים ותיקיות שונות, לא עזר.

**Comment by ShmuelRonen** [comment]
ומה קורה כשאתה פותח דף בדפדפן עם זה:http://127.0.0.1:7860/

**Comment by UberStorm** [comment]
> ומה קורה כשאתה פותח דף בדפדפן עם זה:http://127.0.0.1:7860/

אולי לא הסברתי כמו שצריך, אבל הGUI כן עולה לי.
לאחר שאני מכניס אודיו ולוחץ על SUMBIT, אני מקבל את ההודעה שהעתקתי והGUI טוען שעות מבלי שמתקבלת תוצאת תמלול/תרגום.
כלומר, הוויספר לא רץ בפועל לאחר לחיצה על SUMBIT אצלי...
![image](https://github.com/ShmuelRonen/hebrew_whisper/assets/147564504/f683b671-efb5-42b4-9602-6b7eb72af794)

**Comment by UberStorm** [comment]
(venv) E:\RVC\hebrew_whisper>python app.py
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.17s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\maorg\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\maorg\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\routing.py", line 75, in app
    await response(scope, receive, send)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\responses.py", line 352, in __call__
    await send(
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\_exception_handler.py", line 50, in sender
    await send(message)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\starlette\middleware\errors.py", line 161, in _send
    await send(message)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 504, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\h11\_connection.py", line 469, in send
    data_list = self.send_with_data_passthrough(event)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\h11\_connection.py", line 502, in send_with_data_passthrough
    writer(event, data_list.append)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\h11\_writers.py", line 77, in __call__
    self.send_data(event.data, write)
  File "E:\RVC\hebrew_whisper\venv\lib\site-packages\h11\_writers.py", line 97, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.
E:\RVC\hebrew_whisper\venv\lib\site-packages\transformers\models\whisper\modeling_whisper.py:694: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

**Comment by ShmuelRonen** [comment]
מצב זה קורה בכל קובץ אודיו?

**Comment by UberStorm** [comment]
חוץ מהחלק האחרון שאני אצטט בעוד רגע, בקבצי אודיו מסוימים לא מופיעות שלל השגיאות שיש למעלה. אולי קשור לקידוד האודיו. אבל עדיין לא עובד גם כשאין את השגיאות האלה.



Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.
E:\RVC\hebrew_whisper\venv\lib\site-packages\transformers\models\whisper\modeling_whisper.py:694: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

**Comment by ShmuelRonen** [comment]
האם אף קובץ אודיו לא יוצר transcribe או translate?

**Comment by UberStorm** [comment]
כן, זה לא עובד עם אף קובץ. ניסיתי כמה בקידודים שונים.
ניסיתי להחליף את גרסת הTORCH לגרסת 2.1.2 + cuda 11.8
והשגיאה האחרונה נעלמה, אבל התמלול/תרגום עצמם עדיין לא עובדים וזה טוען "לנצח".

Requirements installed.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:19<00:00,  9.90s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.
![image](https://github.com/ShmuelRonen/hebrew_whisper/assets/147564504/4dc80ef2-e2d2-481c-8e4a-f512e3c32a26)

**Comment by ShmuelRonen** [comment]
כפי שכתבתי בהתחלה אינני יכול לשחזר את הבעיה אצלי. אולי תתקין את הריפוזיטורי עם סביבה וויטואלית של Anaconda

**Comment by UberStorm** [comment]
לא עובד לי גם דרך אנקונדה.
באילו גרסאות פייתון וטורץ' אתה משתמש בסביבה שלך?

**Comment by ShmuelRonen** [comment]
(venv) E:\hebrew wispher>python
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

(venv) E:\hebrew wispher>pip show torch
Name: torch
Version: 2.2.2+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: e:\hebrew wispher\venv\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: openai-whisper, torchaudio, torchvision

(venv) E:\hebrew wispher>
